Service implementation
TheBoyzzzzzz/MAUI pull request #15
Opened 2023-04-16 16:43 UTC by OlegErshov

2023-04-16 16:46 UTC, Tivlas commented on StaffManager/StaffManager.Application/Services/PositionResponsibilityService.cs
> +            _unitOfWork = unit;
Просто для красоты не надо оставлять столько пустых строк

2023-04-16 16:54 UTC, Tivlas requested changes
Разве в асинхронных методах не нужно писать await? И по-моему нет смысла писать return если метод возвращает Task

2023-04-16 18:32 UTC, Tivlas approved these changes

2023-04-16 18:43 UTC, Tivlas commented on StaffManager/StaffManager.Application/Services/PositionResponsibilityService.cs
> +            return _unitOfWork.PositionResponsibilityRepository.DeleteAsync(item);
не переданы все параметры

2023-04-16 18:43 UTC, Tivlas commented on StaffManager/StaffManager.Application/Services/PositionResponsibilityService.cs
> +            return _unitOfWork.PositionResponsibilityRepository.GetByIdAsync(id);
не переданы все параметры

2023-04-16 18:44 UTC, Tivlas commented on StaffManager/StaffManager.Application/Services/PositionResponsibilityService.cs
> +            return _unitOfWork.PositionResponsibilityRepository.ListAsync(filter);
не переданы все параметры

2023-04-16 18:48 UTC, Tivlas commented on StaffManager/StaffManager.Application/Services/PositionService.cs
> +            var res = pos.Select(x => x.PositionResponsibilities).First().ToList().AsReadOnly();
По моему у парней в этом методе в субботу были какие то траблы, так что вскоре узнаем рабочий ли это код

2023-04-16 18:49 UTC, Tivlas requested changes
Возможные ошибки указаны в комментариях

2023-04-17 15:23 UTC, SergeyBrykulskii approved these changes

2023-04-17 15:31 UTC, Tivlas approved these changes
Вроде норм, если потом упадет то сори

2023-04-17 15:32 UTC, merged