Picker
TheBoyzzzzzz/MAUI pull request #20
Opened 2023-04-24 10:11 UTC by OlegErshov

Вроде работает

2023-04-24 18:58 UTC, Tivlas commented on StaffManager/StaffManager.UI/ViewModels/PositionsViewModel.cs
> +    public ObservableCollection<PositionResponsibility> PositionResponsibilities {
я думаю что смысла в двух строках тут мало, перенеси на одну

2023-04-24 19:01 UTC, Tivlas commented on StaffManager/StaffManager.UI/Pages/Positions.xaml
> +                <DataTemplate x:Name="SushiItem"
какой суши айтем)

2023-04-24 19:05 UTC, Tivlas requested changes
В основном просто имена поменять нужно (вроде все в комментах указал). И можете перед PR выполнять Code CleanUp (ПКМ по проекту), но мб конфликты будут. Поэтому можете в файлах которые трогали вручную удалять ненужные строки и т.д. Можешь заодно и поправить отображение текста (то о чем в телеге говорили)

2023-04-24 20:42 UTC, Tivlas commented
Сергей можешь чекнуть, а то мы с Олежей можем не заметить недочет, тк уже видели код

2023-04-25 07:09 UTC, SergeyBrykulskii approved these changes

2023-04-25 07:57 UTC, Tivlas approved these changes

2023-04-25 07:59 UTC, merged